routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('posts', 'PostController');

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'body',
        'published_at',
    ];


    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'user_id',
        'photo',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'published_at',
    ];


    /**
     * Get list of the published posts
     *
     * @return mixed
     */
    public function getPublishedPosts()
    {
        return $this->published()
                    ->orderBy('published_at', 'desc')
                    ->paginate(5);
    }

    /**
     * Get all user posts
     *
     * @param $userId
     * @return mixed
     */
    public function getUserPosts($userId)
    {
        return $this->where('user_id', $userId)
                    ->orderBy('published_at', 'desc')
                    ->paginate(5);
    }

    /**
     * Scope for filter only already published posts by date
     *
     * @param $query
     */
    public function scopePublished($query)
    {
        $query->where('published_at', '<=', Carbon::now());
    }

    /**
     * Get post author profile
     *
     * @return mixed
     */
    public function author()
    {
        return $this->hasOne('App\Models\User','id','user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the published posts.
     *
     * @param Post $postModel
     * @return \Illuminate\Http\Response
     */
    public function index(Post $postModel)
    {
        $posts = $postModel->getPublishedPosts();
        return view('home', compact('posts'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BlogPostRequest;
use Auth;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the posts.
     *
     * @param Post $postModel
     * @return \Illuminate\Http\Response
     */
    public function index(Post $postModel)
    {
        $userId = Auth::id();
        $posts = $postModel->getUserPosts($userId);
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  BlogPostRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogPostRequest $request)
    {
        $post = new Post();
        $post->fill($request->all());
        $post->user_id = Auth::id();
        if ($request->photo) {
            $post->photo = $request->photo->store('posts');
        }
        $post->save();
        return redirect()->route('home');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        if (!$post || $post->user_id != Auth::id()) {
            return redirect()->route('home');
        }
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  BlogPostRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogPostRequest $request, $id)
    {
        $post = Post::find($id);

        if (!$post || $post->user_id != Auth::id()) {
            return redirect()->route('home');
        }

        $post->fill($request->all());
        if ($request->photo) {
            Storage::delete($post->photo);
            $post->photo = $request->photo->store('posts');
        }
        $post->save();

        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        if ($post && $post->user_id == Auth::id()) {
            Storage::delete($post->photo);
            $post->delete();
        }

        return redirect()->back();

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Blog Posts</h2>
                    </div>

                    <div class="panel-body">
                        <div class="text-right">
                            <a href="{{ route('posts.create') }}" class="btn btn-primary">+ Add New</a>
                        </div>
                    </div>
                </div>

                @foreach($posts as $post)
                    @include('posts._post')
                @endforeach

                <div class="text-center">
                    {!! $posts->render() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Small Blog') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ route('home') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('posts.index') }}">My Posts</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/posts/_form.blade.php
<div class="form-group">
    {!! Form::label('Title *') !!}
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
    @if ($errors->has('title'))
        <span class="help-block">
            <strong>{{ $errors->first('title') }}</strong>
        </span>
    @endif
</div>
<div class="form-group">
    {!! Form::label('Body *') !!}
    {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
    @if ($errors->has('body'))
        <span class="help-block">
            <strong>{{ $errors->first('body') }}</strong>
        </span>
    @endif
</div>
<div class="form-group">
    {!! Form::label('Photo') !!}
    @if (isset($post))
        <div><img class="photo-small" src="/storage/{{ $post->photo }}"/></div>
    @endif
    {!! Form::file('photo', ['photo'=>'mimes:jpg,jpeg,bmp,png,gif|max:200']) !!}
    @if ($errors->has('photo'))
        <span class="help-block">
            <strong>{{ $errors->first('photo') }}</strong>
        </span>
    @endif
</div>
<div class="form-group">
    {!! Form::label('Date posted') !!}
    {!! Form::input('date', 'published_at', isset($post) ? Carbon\Carbon::parse($post->published_at)->format('Y-m-d') : date('Y-m-d'), ['class'=>'form-control']) !!}
    @if ($errors->has('published_at'))
        <span class="help-block">
            <strong>{{ $errors->first('published_at') }}</strong>
        </span>
    @endif
</div>
<div class="form-group">
    {!! Form::submit('Save', ['class'=>'btn btn-success']) !!}
    <a href="{{ url()->previous() ? url()->previous() : route('posts.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/posts/_post.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>{{ $post->title }} <span class="published-at">| {{ Carbon\Carbon::parse($post->published_at)->format('d-m-Y, l') }} | {{ $post->author->name }}</span></h4>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                {!! nl2br($post->body) !!}
            </div>
            <div class="col-md-6">
                <img src="/storage/{{ $post->photo }}" class="post-photo">
            </div>
            @if ($post->user_id == Auth::id())
                <div class="col-md-12 text-right">
                    {!! Form::open(['url' => route('posts.destroy', $post->id), 'class' => 'inline-block', 'method' => 'delete']) !!}
                    {!! Form::submit('Delete',['class'=>'btn btn-danger']) !!}
                    {!! Form::close() !!}
                    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default">Edit</a>
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Add Post</h3>
                    </div>

                    <div class="panel-body">

                        {!! Form::open(['route'=>'posts.store','files' => true]) !!}
                        @include('posts._form')
                        {!! Form::close()!!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Edit Post</h3>
                    </div>

                    <div class="panel-body">

                        {!! Form::model($post, ['method'=>'PATCH','route'=>['posts.update', $post->id], 'files' => true]) !!}
                        @include('posts._form')
                        {!! Form::close()!!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>My Posts</h2>
                    </div>
                    <div class="panel-body">
                        <div class="text-right">
                            <a href="{{ route('posts.create') }}" class="btn btn-primary">+ Add New</a>
                        </div>
                    </div>
                </div>

                @foreach($posts as $post)
                    @include('posts._post')
                @endforeach

                <div class="text-center">
                    {!! $posts->render() !!}
                </div>
            </div>
        </div>
    </div>
@endsection